// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: runner.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gauge.Messages {

  /// <summary>Holder for reflection information generated from runner.proto</summary>
  public static partial class RunnerReflection {

    #region Descriptor
    /// <summary>File descriptor for runner.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RunnerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxydW5uZXIucHJvdG8SDmdhdWdlLm1lc3NhZ2VzGg5tZXNzYWdlcy5wcm90",
            "bzK2EAoGUnVubmVyElkKDFZhbGlkYXRlU3RlcBIjLmdhdWdlLm1lc3NhZ2Vz",
            "LlN0ZXBWYWxpZGF0ZVJlcXVlc3QaJC5nYXVnZS5tZXNzYWdlcy5TdGVwVmFs",
            "aWRhdGVSZXNwb25zZRJUChJTdWl0ZURhdGFTdG9yZUluaXQSFS5nYXVnZS5t",
            "ZXNzYWdlcy5FbXB0eRonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXR1",
            "c1Jlc3BvbnNlEmYKEUV4ZWN1dGlvblN0YXJ0aW5nEiguZ2F1Z2UubWVzc2Fn",
            "ZXMuRXhlY3V0aW9uU3RhcnRpbmdSZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMu",
            "RXhlY3V0aW9uU3RhdHVzUmVzcG9uc2USUwoRU3BlY0RhdGFTdG9yZUluaXQS",
            "FS5nYXVnZS5tZXNzYWdlcy5FbXB0eRonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1",
            "dGlvblN0YXR1c1Jlc3BvbnNlEm4KFVNwZWNFeGVjdXRpb25TdGFydGluZxIs",
            "LmdhdWdlLm1lc3NhZ2VzLlNwZWNFeGVjdXRpb25TdGFydGluZ1JlcXVlc3Qa",
            "Jy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJXChVT",
            "Y2VuYXJpb0RhdGFTdG9yZUluaXQSFS5nYXVnZS5tZXNzYWdlcy5FbXB0eRon",
            "LmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3BvbnNlEnYKGVNj",
            "ZW5hcmlvRXhlY3V0aW9uU3RhcnRpbmcSMC5nYXVnZS5tZXNzYWdlcy5TY2Vu",
            "YXJpb0V4ZWN1dGlvblN0YXJ0aW5nUmVxdWVzdBonLmdhdWdlLm1lc3NhZ2Vz",
            "LkV4ZWN1dGlvblN0YXR1c1Jlc3BvbnNlEm4KFVN0ZXBFeGVjdXRpb25TdGFy",
            "dGluZxIsLmdhdWdlLm1lc3NhZ2VzLlN0ZXBFeGVjdXRpb25TdGFydGluZ1Jl",
            "cXVlc3QaJy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25z",
            "ZRJaCgtFeGVjdXRlU3RlcBIiLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGVTdGVw",
            "UmVxdWVzdBonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3Bv",
            "bnNlEmoKE1N0ZXBFeGVjdXRpb25FbmRpbmcSKi5nYXVnZS5tZXNzYWdlcy5T",
            "dGVwRXhlY3V0aW9uRW5kaW5nUmVxdWVzdBonLmdhdWdlLm1lc3NhZ2VzLkV4",
            "ZWN1dGlvblN0YXR1c1Jlc3BvbnNlEnIKF1NjZW5hcmlvRXhlY3V0aW9uRW5k",
            "aW5nEi4uZ2F1Z2UubWVzc2FnZXMuU2NlbmFyaW9FeGVjdXRpb25FbmRpbmdS",
            "ZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVzcG9u",
            "c2USagoTU3BlY0V4ZWN1dGlvbkVuZGluZxIqLmdhdWdlLm1lc3NhZ2VzLlNw",
            "ZWNFeGVjdXRpb25FbmRpbmdSZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMuRXhl",
            "Y3V0aW9uU3RhdHVzUmVzcG9uc2USYgoPRXhlY3V0aW9uRW5kaW5nEiYuZ2F1",
            "Z2UubWVzc2FnZXMuRXhlY3V0aW9uRW5kaW5nUmVxdWVzdBonLmdhdWdlLm1l",
            "c3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3BvbnNlElMKDEdldFN0ZXBOYW1l",
            "cxIgLmdhdWdlLm1lc3NhZ2VzLlN0ZXBOYW1lc1JlcXVlc3QaIS5nYXVnZS5t",
            "ZXNzYWdlcy5TdGVwTmFtZXNSZXNwb25zZRJECglDYWNoZUZpbGUSIC5nYXVn",
            "ZS5tZXNzYWdlcy5DYWNoZUZpbGVSZXF1ZXN0GhUuZ2F1Z2UubWVzc2FnZXMu",
            "RW1wdHkSXwoQR2V0U3RlcFBvc2l0aW9ucxIkLmdhdWdlLm1lc3NhZ2VzLlN0",
            "ZXBQb3NpdGlvbnNSZXF1ZXN0GiUuZ2F1Z2UubWVzc2FnZXMuU3RlcFBvc2l0",
            "aW9uc1Jlc3BvbnNlEl8KFkdldEltcGxlbWVudGF0aW9uRmlsZXMSFS5nYXVn",
            "ZS5tZXNzYWdlcy5FbXB0eRouLmdhdWdlLm1lc3NhZ2VzLkltcGxlbWVudGF0",
            "aW9uRmlsZUxpc3RSZXNwb25zZRJYCg1JbXBsZW1lbnRTdHViEi0uZ2F1Z2Uu",
            "bWVzc2FnZXMuU3R1YkltcGxlbWVudGF0aW9uQ29kZVJlcXVlc3QaGC5nYXVn",
            "ZS5tZXNzYWdlcy5GaWxlRGlmZhJQCgtHZXRTdGVwTmFtZRIfLmdhdWdlLm1l",
            "c3NhZ2VzLlN0ZXBOYW1lUmVxdWVzdBogLmdhdWdlLm1lc3NhZ2VzLlN0ZXBO",
            "YW1lUmVzcG9uc2USXwoPR2V0R2xvYlBhdHRlcm5zEhUuZ2F1Z2UubWVzc2Fn",
            "ZXMuRW1wdHkaNS5nYXVnZS5tZXNzYWdlcy5JbXBsZW1lbnRhdGlvbkZpbGVH",
            "bG9iUGF0dGVyblJlc3BvbnNlEk0KCFJlZmFjdG9yEh8uZ2F1Z2UubWVzc2Fn",
            "ZXMuUmVmYWN0b3JSZXF1ZXN0GiAuZ2F1Z2UubWVzc2FnZXMuUmVmYWN0b3JS",
            "ZXNwb25zZRJICgtLaWxsUHJvY2VzcxIiLmdhdWdlLm1lc3NhZ2VzLktpbGxQ",
            "cm9jZXNzUmVxdWVzdBoVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5QikKFmNvbS50",
            "aG91Z2h0d29ya3MuZ2F1Z2WqAg5HYXVnZS5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gauge.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
