// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gauge.Messages {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIOZ2F1Z2UubWVzc2FnZXMaDm1lc3NhZ2VzLnBy",
            "b3RvMuEJCglFeGVjdXRpb24SWgoYSW5pdGlhbGl6ZVN1aXRlRGF0YVN0b3Jl",
            "EhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkaJy5nYXVnZS5tZXNzYWdlcy5FeGVj",
            "dXRpb25TdGF0dXNSZXNwb25zZRJjCg5TdGFydEV4ZWN1dGlvbhIoLmdhdWdl",
            "Lm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXJ0aW5nUmVxdWVzdBonLmdhdWdlLm1l",
            "c3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3BvbnNlElkKF0luaXRpYWxpemVT",
            "cGVjRGF0YVN0b3JlEhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkaJy5nYXVnZS5t",
            "ZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJrChJTdGFydFNwZWNF",
            "eGVjdXRpb24SLC5nYXVnZS5tZXNzYWdlcy5TcGVjRXhlY3V0aW9uU3RhcnRp",
            "bmdSZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVz",
            "cG9uc2USXQobSW5pdGlhbGl6ZVNjZW5hcmlvRGF0YVN0b3JlEhUuZ2F1Z2Uu",
            "bWVzc2FnZXMuRW1wdHkaJy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0",
            "dXNSZXNwb25zZRJzChZTdGFydFNjZW5hcmlvRXhlY3V0aW9uEjAuZ2F1Z2Uu",
            "bWVzc2FnZXMuU2NlbmFyaW9FeGVjdXRpb25TdGFydGluZ1JlcXVlc3QaJy5n",
            "YXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJrChJTdGFy",
            "dFN0ZXBFeGVjdXRpb24SLC5nYXVnZS5tZXNzYWdlcy5TdGVwRXhlY3V0aW9u",
            "U3RhcnRpbmdSZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3Rh",
            "dHVzUmVzcG9uc2USWgoLRXhlY3V0ZVN0ZXASIi5nYXVnZS5tZXNzYWdlcy5F",
            "eGVjdXRlU3RlcFJlcXVlc3QaJy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25T",
            "dGF0dXNSZXNwb25zZRJqChNGaW5pc2hTdGVwRXhlY3V0aW9uEiouZ2F1Z2Uu",
            "bWVzc2FnZXMuU3RlcEV4ZWN1dGlvbkVuZGluZ1JlcXVlc3QaJy5nYXVnZS5t",
            "ZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJyChdGaW5pc2hTY2Vu",
            "YXJpb0V4ZWN1dGlvbhIuLmdhdWdlLm1lc3NhZ2VzLlNjZW5hcmlvRXhlY3V0",
            "aW9uRW5kaW5nUmVxdWVzdBonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0",
            "YXR1c1Jlc3BvbnNlEmoKE0ZpbmlzaFNwZWNFeGVjdXRpb24SKi5nYXVnZS5t",
            "ZXNzYWdlcy5TcGVjRXhlY3V0aW9uRW5kaW5nUmVxdWVzdBonLmdhdWdlLm1l",
            "c3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3BvbnNlEmIKD0ZpbmlzaEV4ZWN1",
            "dGlvbhImLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvbkVuZGluZ1JlcXVlc3Qa",
            "Jy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZTLEBQoJ",
            "QXV0aG9yaW5nEkQKCUNhY2hlRmlsZRIgLmdhdWdlLm1lc3NhZ2VzLkNhY2hl",
            "RmlsZVJlcXVlc3QaFS5nYXVnZS5tZXNzYWdlcy5FbXB0eRJQCgtHZXRTdGVw",
            "TmFtZRIfLmdhdWdlLm1lc3NhZ2VzLlN0ZXBOYW1lUmVxdWVzdBogLmdhdWdl",
            "Lm1lc3NhZ2VzLlN0ZXBOYW1lUmVzcG9uc2USXwoPR2V0R2xvYlBhdHRlcm5z",
            "EhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkaNS5nYXVnZS5tZXNzYWdlcy5JbXBs",
            "ZW1lbnRhdGlvbkZpbGVHbG9iUGF0dGVyblJlc3BvbnNlElMKDEdldFN0ZXBO",
            "YW1lcxIgLmdhdWdlLm1lc3NhZ2VzLlN0ZXBOYW1lc1JlcXVlc3QaIS5nYXVn",
            "ZS5tZXNzYWdlcy5TdGVwTmFtZXNSZXNwb25zZRJfChBHZXRTdGVwUG9zaXRp",
            "b25zEiQuZ2F1Z2UubWVzc2FnZXMuU3RlcFBvc2l0aW9uc1JlcXVlc3QaJS5n",
            "YXVnZS5tZXNzYWdlcy5TdGVwUG9zaXRpb25zUmVzcG9uc2USXwoWR2V0SW1w",
            "bGVtZW50YXRpb25GaWxlcxIVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5Gi4uZ2F1",
            "Z2UubWVzc2FnZXMuSW1wbGVtZW50YXRpb25GaWxlTGlzdFJlc3BvbnNlElgK",
            "DUltcGxlbWVudFN0dWISLS5nYXVnZS5tZXNzYWdlcy5TdHViSW1wbGVtZW50",
            "YXRpb25Db2RlUmVxdWVzdBoYLmdhdWdlLm1lc3NhZ2VzLkZpbGVEaWZmEk0K",
            "CFJlZmFjdG9yEh8uZ2F1Z2UubWVzc2FnZXMuUmVmYWN0b3JSZXF1ZXN0GiAu",
            "Z2F1Z2UubWVzc2FnZXMuUmVmYWN0b3JSZXNwb25zZTJaCgZSZXN1bHQSUAoR",
            "Tm90aWZ5U3VpdGVSZXN1bHQSJC5nYXVnZS5tZXNzYWdlcy5TdWl0ZUV4ZWN1",
            "dGlvblJlc3VsdBoVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5MmYKCVZhbGlkYXRv",
            "chJZCgxWYWxpZGF0ZVN0ZXASIy5nYXVnZS5tZXNzYWdlcy5TdGVwVmFsaWRh",
            "dGVSZXF1ZXN0GiQuZ2F1Z2UubWVzc2FnZXMuU3RlcFZhbGlkYXRlUmVzcG9u",
            "c2UyTAoHUHJvY2VzcxJBCgRLaWxsEiIuZ2F1Z2UubWVzc2FnZXMuS2lsbFBy",
            "b2Nlc3NSZXF1ZXN0GhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHlCKQoWY29tLnRo",
            "b3VnaHR3b3Jrcy5nYXVnZaoCDkdhdWdlLk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gauge.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
