// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gauge.Messages {

  /// <summary>Holder for reflection information generated from services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5zZXJ2aWNlcy5wcm90bxIOZ2F1Z2UubWVzc2FnZXMaDm1lc3NhZ2VzLnBy",
            "b3RvMrUQCgZSdW5uZXISWQoMVmFsaWRhdGVTdGVwEiMuZ2F1Z2UubWVzc2Fn",
            "ZXMuU3RlcFZhbGlkYXRlUmVxdWVzdBokLmdhdWdlLm1lc3NhZ2VzLlN0ZXBW",
            "YWxpZGF0ZVJlc3BvbnNlEloKGEluaXRpYWxpemVTdWl0ZURhdGFTdG9yZRIV",
            "LmdhdWdlLm1lc3NhZ2VzLkVtcHR5GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0",
            "aW9uU3RhdHVzUmVzcG9uc2USYwoOU3RhcnRFeGVjdXRpb24SKC5nYXVnZS5t",
            "ZXNzYWdlcy5FeGVjdXRpb25TdGFydGluZ1JlcXVlc3QaJy5nYXVnZS5tZXNz",
            "YWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJZChdJbml0aWFsaXplU3Bl",
            "Y0RhdGFTdG9yZRIVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5GicuZ2F1Z2UubWVz",
            "c2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVzcG9uc2USawoSU3RhcnRTcGVjRXhl",
            "Y3V0aW9uEiwuZ2F1Z2UubWVzc2FnZXMuU3BlY0V4ZWN1dGlvblN0YXJ0aW5n",
            "UmVxdWVzdBonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXR1c1Jlc3Bv",
            "bnNlEl0KG0luaXRpYWxpemVTY2VuYXJpb0RhdGFTdG9yZRIVLmdhdWdlLm1l",
            "c3NhZ2VzLkVtcHR5GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3RhdHVz",
            "UmVzcG9uc2UScwoWU3RhcnRTY2VuYXJpb0V4ZWN1dGlvbhIwLmdhdWdlLm1l",
            "c3NhZ2VzLlNjZW5hcmlvRXhlY3V0aW9uU3RhcnRpbmdSZXF1ZXN0GicuZ2F1",
            "Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVzcG9uc2USawoSU3RhcnRT",
            "dGVwRXhlY3V0aW9uEiwuZ2F1Z2UubWVzc2FnZXMuU3RlcEV4ZWN1dGlvblN0",
            "YXJ0aW5nUmVxdWVzdBonLmdhdWdlLm1lc3NhZ2VzLkV4ZWN1dGlvblN0YXR1",
            "c1Jlc3BvbnNlEloKC0V4ZWN1dGVTdGVwEiIuZ2F1Z2UubWVzc2FnZXMuRXhl",
            "Y3V0ZVN0ZXBSZXF1ZXN0GicuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3Rh",
            "dHVzUmVzcG9uc2USagoTRmluaXNoU3RlcEV4ZWN1dGlvbhIqLmdhdWdlLm1l",
            "c3NhZ2VzLlN0ZXBFeGVjdXRpb25FbmRpbmdSZXF1ZXN0GicuZ2F1Z2UubWVz",
            "c2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVzcG9uc2UScgoXRmluaXNoU2NlbmFy",
            "aW9FeGVjdXRpb24SLi5nYXVnZS5tZXNzYWdlcy5TY2VuYXJpb0V4ZWN1dGlv",
            "bkVuZGluZ1JlcXVlc3QaJy5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25TdGF0",
            "dXNSZXNwb25zZRJqChNGaW5pc2hTcGVjRXhlY3V0aW9uEiouZ2F1Z2UubWVz",
            "c2FnZXMuU3BlY0V4ZWN1dGlvbkVuZGluZ1JlcXVlc3QaJy5nYXVnZS5tZXNz",
            "YWdlcy5FeGVjdXRpb25TdGF0dXNSZXNwb25zZRJiCg9GaW5pc2hFeGVjdXRp",
            "b24SJi5nYXVnZS5tZXNzYWdlcy5FeGVjdXRpb25FbmRpbmdSZXF1ZXN0Gicu",
            "Z2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uU3RhdHVzUmVzcG9uc2USRAoJQ2Fj",
            "aGVGaWxlEiAuZ2F1Z2UubWVzc2FnZXMuQ2FjaGVGaWxlUmVxdWVzdBoVLmdh",
            "dWdlLm1lc3NhZ2VzLkVtcHR5ElAKC0dldFN0ZXBOYW1lEh8uZ2F1Z2UubWVz",
            "c2FnZXMuU3RlcE5hbWVSZXF1ZXN0GiAuZ2F1Z2UubWVzc2FnZXMuU3RlcE5h",
            "bWVSZXNwb25zZRJfCg9HZXRHbG9iUGF0dGVybnMSFS5nYXVnZS5tZXNzYWdl",
            "cy5FbXB0eRo1LmdhdWdlLm1lc3NhZ2VzLkltcGxlbWVudGF0aW9uRmlsZUds",
            "b2JQYXR0ZXJuUmVzcG9uc2USUwoMR2V0U3RlcE5hbWVzEiAuZ2F1Z2UubWVz",
            "c2FnZXMuU3RlcE5hbWVzUmVxdWVzdBohLmdhdWdlLm1lc3NhZ2VzLlN0ZXBO",
            "YW1lc1Jlc3BvbnNlEl8KEEdldFN0ZXBQb3NpdGlvbnMSJC5nYXVnZS5tZXNz",
            "YWdlcy5TdGVwUG9zaXRpb25zUmVxdWVzdBolLmdhdWdlLm1lc3NhZ2VzLlN0",
            "ZXBQb3NpdGlvbnNSZXNwb25zZRJfChZHZXRJbXBsZW1lbnRhdGlvbkZpbGVz",
            "EhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkaLi5nYXVnZS5tZXNzYWdlcy5JbXBs",
            "ZW1lbnRhdGlvbkZpbGVMaXN0UmVzcG9uc2USWAoNSW1wbGVtZW50U3R1YhIt",
            "LmdhdWdlLm1lc3NhZ2VzLlN0dWJJbXBsZW1lbnRhdGlvbkNvZGVSZXF1ZXN0",
            "GhguZ2F1Z2UubWVzc2FnZXMuRmlsZURpZmYSTQoIUmVmYWN0b3ISHy5nYXVn",
            "ZS5tZXNzYWdlcy5SZWZhY3RvclJlcXVlc3QaIC5nYXVnZS5tZXNzYWdlcy5S",
            "ZWZhY3RvclJlc3BvbnNlEkEKBEtpbGwSIi5nYXVnZS5tZXNzYWdlcy5LaWxs",
            "UHJvY2Vzc1JlcXVlc3QaFS5nYXVnZS5tZXNzYWdlcy5FbXB0eTKvBwoIUmVw",
            "b3J0ZXISWgoXTm90aWZ5RXhlY3V0aW9uU3RhcnRpbmcSKC5nYXVnZS5tZXNz",
            "YWdlcy5FeGVjdXRpb25TdGFydGluZ1JlcXVlc3QaFS5nYXVnZS5tZXNzYWdl",
            "cy5FbXB0eRJiChtOb3RpZnlTcGVjRXhlY3V0aW9uU3RhcnRpbmcSLC5nYXVn",
            "ZS5tZXNzYWdlcy5TcGVjRXhlY3V0aW9uU3RhcnRpbmdSZXF1ZXN0GhUuZ2F1",
            "Z2UubWVzc2FnZXMuRW1wdHkSagofTm90aWZ5U2NlbmFyaW9FeGVjdXRpb25T",
            "dGFydGluZxIwLmdhdWdlLm1lc3NhZ2VzLlNjZW5hcmlvRXhlY3V0aW9uU3Rh",
            "cnRpbmdSZXF1ZXN0GhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkSYgobTm90aWZ5",
            "U3RlcEV4ZWN1dGlvblN0YXJ0aW5nEiwuZ2F1Z2UubWVzc2FnZXMuU3RlcEV4",
            "ZWN1dGlvblN0YXJ0aW5nUmVxdWVzdBoVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5",
            "El4KGU5vdGlmeVN0ZXBFeGVjdXRpb25FbmRpbmcSKi5nYXVnZS5tZXNzYWdl",
            "cy5TdGVwRXhlY3V0aW9uRW5kaW5nUmVxdWVzdBoVLmdhdWdlLm1lc3NhZ2Vz",
            "LkVtcHR5EmYKHU5vdGlmeVNjZW5hcmlvRXhlY3V0aW9uRW5kaW5nEi4uZ2F1",
            "Z2UubWVzc2FnZXMuU2NlbmFyaW9FeGVjdXRpb25FbmRpbmdSZXF1ZXN0GhUu",
            "Z2F1Z2UubWVzc2FnZXMuRW1wdHkSXgoZTm90aWZ5U3BlY0V4ZWN1dGlvbkVu",
            "ZGluZxIqLmdhdWdlLm1lc3NhZ2VzLlNwZWNFeGVjdXRpb25FbmRpbmdSZXF1",
            "ZXN0GhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHkSVgoVTm90aWZ5RXhlY3V0aW9u",
            "RW5kaW5nEiYuZ2F1Z2UubWVzc2FnZXMuRXhlY3V0aW9uRW5kaW5nUmVxdWVz",
            "dBoVLmdhdWdlLm1lc3NhZ2VzLkVtcHR5ElAKEU5vdGlmeVN1aXRlUmVzdWx0",
            "EiQuZ2F1Z2UubWVzc2FnZXMuU3VpdGVFeGVjdXRpb25SZXN1bHQaFS5nYXVn",
            "ZS5tZXNzYWdlcy5FbXB0eRJBCgRLaWxsEiIuZ2F1Z2UubWVzc2FnZXMuS2ls",
            "bFByb2Nlc3NSZXF1ZXN0GhUuZ2F1Z2UubWVzc2FnZXMuRW1wdHlCKQoWY29t",
            "LnRob3VnaHR3b3Jrcy5nYXVnZaoCDkdhdWdlLk1lc3NhZ2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gauge.Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
